# Makefile for the focaltech touchscreen drivers.


obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)	+=  focaltech_core.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)	+=  focaltech_ex_fun.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)	+=  focaltech_ex_mode.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)	+=  focaltech_gesture.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)	+=  focaltech_esdcheck.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)   +=  focaltech_point_report_check.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)   +=  focaltech_test/

obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)   +=  focaltech_i2c.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)	+=  focaltech_flash.o
obj-$(CONFIG_TOUCHSCREEN_FTS_LAUREL)   +=  focaltech_flash/
