# Goodix Touchscreen Makefile
# This Makefile is only for tempory compiling use
# Use xxxproject/Makefile-release when release driver
#
# core layer

obj-$(CONFIG_TOUCHSCREEN_GOODIX_LAUREL)           += goodix_ts_i2c.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_LAUREL)           += goodix_ts_core.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_LAUREL)           += goodix_cfg_bin.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_LAUREL)           += goodix_ts_test.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_LAUREL_UPDATE)    += goodix_gtx8_update.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_LAUREL_GESTURE)   += goodix_ts_gesture.o
obj-$(CONFIG_TOUCHSCREEN_GOODIX_LAUREL_TOOLS)     += goodix_ts_tools.o
